language: go

go:
  - 1.8
  - 1.9

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - dep ensure

before_script:
  - go vet
  - golint

script:
  - go test -v
