required = ["github.com/golang/lint/golint"]

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/tcnksm/go-holidayjp"

[[constraint]]
  branch = "master"
  name = "github.com/y-yagi/goext"
