version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/y-yagi/jpcal

    steps:
      - checkout
      - run:
          name : Run dep
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
      - run:
          name: Run vet
          command: go vet
      - run:
          name: Run lint
          command: |
            go build ./vendor/github.com/golang/lint/golint
            ./golint -set_exit_status
      - run:
          name: Run tests
          command: go test -v
      - deploy:
          name: Continuous dep update
          command: |
            go get -u github.com/y-yagi/ci-dep-update
            ci-dep-update -u y-yagi -r y-yagi/jpcal

workflows:
  version: 2
  build:
    jobs:
      - build:
          # snip
  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master
    jobs:
      - continuous_dep_update
